apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qjava
  janus-idp.io/tekton: qjava
  backstage.io/kubernetes-id: qjava
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qjava
resources: 
- deployment.yaml
- route.yaml
- service.yaml
