apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: qjava
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qjava 
  name: qjava
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: qjava
    weight: 100 
