apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: qjava-on-pull-request-promotion
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]" 
    pipelinesascode.tekton.dev/pipeline: ".tekton/pull-request-validate.yaml"
    pipelinesascode.tekton.dev/task-0: ".tekton/gather-deploy-images.yaml"  
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/redhat-appstudio/tssc-sample-pipelines/main/pac/tasks/git-clone.yaml"
    #pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/jduimovich/tssc-sample-pipelines/workbranch/pac/tasks/verify-enterprise-contract.yaml"
    pipelinesascode.tekton.dev/task-2: ".tekton/verify-enterprise-contract.yaml"
  labels:
    argocd/app-name: qjava
    janus-idp.io/tekton: qjava
    backstage.io/kubernetes-id: qjava
    backstage.io/kubernetes-namespace: rhtap-app
    app.kubernetes.io/part-of: qjava
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'   
  - name: revision
    value: '{{revision}}'    
  - name: target-branch
    value: '{{target_branch}}'   
  - name: commit-message 
    value: '{{body.pull_request.body}}'
  pipelineRef:
    name: pull-request-validate
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
