apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    pipelines.openshift.io/runtime: generic
    pipelines.openshift.io/strategy: docker
    pipelines.openshift.io/used-by: build-cloud
  name: promotion-flow-pipeline
spec: 
  params:
    - description: Gitops Repo Url 
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string 
    - description: Contents of commit message (push) or pull-request body for PRs
      name: commit-message
      type: string 
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision) 
      taskRef:
        name: git-clone 
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
    - name: handle-promote-action
      params:
        - name: gitops-repo-url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)  
        - name: target-branch
          value: $(params.target-branch)   
        - name: commit-message
          value: $(params.commit-message)  
      runAfter:
        - clone-repository
      taskRef:
        kind: Task
        name: handle-promote-action
      workspaces:
        - name: output
          workspace: workspace  